HAPPY = [
    ['guruvara sanje song', 'a groovy melody'],
    ['heat waves glass animals', 'vibe'],
    ['Girlfriend', 'a cheerful melody'],
    ['I Like Me Better', 'vibe'],
    ['Señorita', 'a catchy song'],
    ['The Nights', 'vibe'],
    ['Peaches (feat. Daniel Caesar)', 'vibe'],
    ['Astronaut In The Ocean', 'a groovy track'],
    ['positions', 'vibe'],
    ['We Don\'t Talk Anymore', 'vibe'],
    ['Don\'t Worry', 'vibe'],
    ['I Wanna Be Yours', 'vibe'],
    ['Nashe Si Chadh Gayi', 'a dance number'],
    ['Sanam', 'a melody'],
    ['Manasilaayo', 'a dance number'],
    ['Chuttamalle', 'a melodious track'],
    ['Aasa Kooda', 'vibe'],
    ['Arabic Kuthu - Halamithi Habibo', 'a catchy song'],
    ['Illuminati - From Aavesham', 'a '],
    ['Chaleya', 'vibe'],
    ['Maate Vinadhuga', 'vibey melody'],
    ['Buttabomma - Telugu', 'dance'],
    ['Rowdy Baby', 'dance'],
    ['Bhool Bhulaivaa 2 Title', 'catchy dance'],
    ['Tauba Tauba (From Bad Newz)', 'catchy dance'],
    ['Jeena Jeena Ya', 'catchy'],
    ['Enjoy Enjaami', 'catchy'],
    ['India Waale', 'dance'],
    ['Dwapara- Krishnam Pranaya', 'catchy melody'],
    ['Nanage Neenu', 'melody'],
    ['Taki Taki (feat. Selena Gomez)', 'catchy'],
    ['Stereo Hearts (feat. Adam Levine)', 'catchy']
]


CALM = [
    ['Let me down slowly', 'vibe'],
    ['samajavaragamana', 'vibe'],
    ['srivali', 'vibe'],
    ['yeh sham mastani', 'old'],
    ['Baani Gondu Elle', 'old'],
    ['Hallu jenu', 'old'],
    ['O Priyathama', 'old'],
    ['Neele Neele Ambar Par Male Version', 'old'],
    ['Nee Sannihake Bandre', 'vibe'],
    ['Jab Tak', 'vibe'],
    ['Minchagi Neenu', 'vibe'],
    ['Tum itna jo muskura rahe ho arth - live', 'old'],
    ['Zara Zara - lofi', 'vibe'],
    ['Tere Liye', 'old'],
    ['O Mere Dil Ke Chain', 'old'],
    ['Agar Tum Mil Jao', 'old'],
    ['Tu Hi Meri Shab Hai', 'old'],
    ['Ninna Ninna Snehake', 'old'],
    ['Feel Good syn cole', 'vibe'],
    ['Janam Janam', 'vibe'],
    ['Munjaane Manjali', 'vibe'],
    ['Mayavi', 'vibe'],
    ['Ninna Gungalli', 'vibe'],
    ['Ninna Danigaagi', 'vibe']
]


ANGER = [
    ['Shiva Tandava stotram', 'divine'],
    ['Kaathalae Kaathalae', 'calm'],
    ['Krishna Flute', 'instrumental'],
    ['Krishna Krish Flute', 'instrumental'],
    ['Nilavinte Neelabhasma', 'calm'],
    ['Two Thousand and Seventeen', 'instrumental'],
    ['Sojugada Soojumallige', 'divine'],
    ['Shree Hari Stotram', 'divine'],
    ['Raga Bagesri', 'classic'],
    ['Mori painjainiya', 'classic'],
    ['Rut Badle', 'classic'],
    ['Sapta Sagaradaache', 'calm'],
    ['Su Wu Tending Sheep', 'instrumental'],
    ['Main Nashe Mein Hoon', 'classic'],
    ['Clair de Lune', 'instrumental'],
    ['We Can Fly', 'instrumental'],
    ['Le Francaise', 'ambient'],
    ['Beach Calmness', 'ambient'],
    ['Weightless', 'ambient'],
    ['Ram Siya Ram', 'divine']
]

SAD = [
    ['Happy-allok', 'a motivational track'],
    ['Kaun Tujhe', 'a feeling song s'],
    ['Preethisuve', 'a romantic track s'],
    ['Tum Hi Ho', 'a romantic track s'],
    ['Why This Kolaveri Di', 'a playful track'],
    ['Agar Tum Saath Ho', 'a feeling song s'],
    ['Roja Jaaneman', 'a feeling song s'],
    ['Idhu Yaaru Bareda Katheya', 'a self-reflective track s'],
    ['Yenagali', 'a motivational melody'],
    ['Olithu Maadu Manusa', 'a motivational melody'],
    ['Kadalanu', 'a calm track'],
    ['Tujh Mein Rab Dikhta Hai', 'a romantic melody s'],
    ['Kanave Unai', 'a feeling song s'],
    ['Nee Thoreda Ghaligeyali', 'a feeling song s'],
    ['Mosa Madalendu Neenu', 'a feeling song s'],
    ['Badri Ki Dulhania', 'an energetic beat to cheer you up!']
]


SURPRISE = [
    ['eye of the tiger-survivor',''],
    ['Starboy', 'a catchy pop song'],
    ['Belageddu-kirik party', 'a catchy melody'],
    ['Don\'t Copy My Flow', 'vibe'],
    ['Oo Antava Oo Oo Antava', 'a dance number!'],
    ['Darshana-From Hridayam', 'vibe'],
    ['Chammak Challo', 'a catchy dance number!'],
    ['Hukum-Thalaivar Alappar', 'a massy track'],
    ['Muqabla', 'a catchy beat'],
    ['Apsara Aali', 'a marathi classic'],
    ['Billie Jean', 'a pop hit!'],
    ['Dangerous-Michael Jackson', 'a pop'],
    ['Ghosts-Michael Jackson', 'pop'],
    ['They Don\'t Really Care About Us-Michael', 'pop'],
    ['Bad 2012-Michael Jackson', 'pop'],
    ['Shape of You', 'a catchy song'],
    ['Thunder', 'Imagine Dragons', 'catchy'],
    ['I Ain\'t Worried-Imagine Dragons', 'vibe'],
    ['Aaj Ki Raat', 'a dance number!'],
    ['Gangnam Style', 'a groovy track'],
    ['Dhan Te Nan', 'a catchy song'],
    ['Bang Bang', 'dance'],
    ['Believer', 'vibe'],
    ['Ugramm Veeram', 'a massy track'],
    ['Tagaru Banthu Tagaru', 'a massy track'],
    ['Mental Ho Jawa-Tagaru', 'a dance number!'],
    ['Badukina Bannave', 'a melody'],
    ['Balma', 'a classical fusion'],
    ['Police Theme-Tagaru', 'a pumped up mass track!'],
    ['Huttidare Kannada', 'an old hit'],
    ['Santhoshakke', 'a groovy song'],
    ['Oyaayiye Yaayiye', 'a melody'],
    ['Surviva', 'a massy track'],
    ['Tum Tum', 'a catchy song'],
    ['Skyfall', 'vibe'],
    ['Cult', 'rage vibe'],
    ['Sunn Raha Hai', 'a melody'],
    ['Family Affair', 'vibe'],
    ['Dham Powere', 'a pumped up mass track!'],
    ['Feeling Good', 'vibe'],
    ['Safari', 'a catchy track'],
    ['Blue Eyes', 'a catchy track'],
    ['Parichayavade', 'a melody']
]
